http.host: "0.0.0.0"
http.port: 9600
log.level: info
path.logs: /var/log/logstash
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50
queue.type: persisted
queue.max_bytes: 1gb
dead_letter_queue.enable: true